### ISSUE TITLE
More HTTP routes than just a SPARQL endpoint

### ISSUE THREAD

**Issue by mikeplus64** [ANU-Linked-Earth-Data/middleware#5]
Probably need an actual reverse proxy for the SPARQL endpoint. Could be part of the Flask routes, in Python, but probably not as performant as say nginx or Apache.

Need to ask what specific URIs schemes we need to support

**Comment by qxcv** [comment]
Things that we'll have to have to support:
- [ ] Observation URIs (so things like https://anulinkedearth.org/datasets/agdc-landsat-8/observation/2013/05/27/23/58/20/cell/R78526/levelSquare-6/levelPixel-8/band-6).
- [ ] A per-dataset metadata page containing all of the supporting RDF data cube definitions. Examples: component specifications, attribute properties, dimension properties, the QB "data set" and "data structure definition", etc. It might make sense to have that all under a prefix of the observation URIs. For instance, we could have all of the QB-related RDF on https://anulinkedearth.org/datasets/agc-landsat-8/.
- [ ] Maybe the `led:` vocabulary we're using, i.e. the page http://www.anulinkedearth.org/sandbox/ANU-LED# containing all of the RDF data for each term. This isn't dataset-specific, so it could just as easily be served from nginx rather than a custom endpoint we have to write.
